export const constants = {
  API_URL: 'https://main.doapp.vn' + '/api/',
};

export const TYPE_ACTION = {
  QR: 'QR',
  SCORE: 'SCORE',
  CALL: 'CALL',
  MESSAGE_TO_SHOP: 'MESSAGE_TO_SHOP',
  VOUCHER: 'VOUCHER',
  PRODUCT_BY_CATEGORY: 'PRODUCT_BY_CATEGORY',
  PRODUCTS_TOP_SALES: 'PRODUCTS_TOP_SALES',
  PRODUCTS_DISCOUNT: 'PRODUCTS_DISCOUNT',
  COMBO: 'COMBO',
  BONUS_PRODUCT: 'BONUS_PRODUCT',
  PRODUCTS_NEW: 'PRODUCTS_NEW',
  LINK: 'LINK',
  PRODUCT: 'PRODUCT',
  CATEGORY_PRODUCT: 'CATEGORY_PRODUCT',
  CATEGORY_POST: 'CATEGORY_POST',
  POST: 'POST',
  SPIN_WHEEL: 'SPIN_WHEEL',
  GUESS_NUMBER: 'GUESS_NUMBER',
};

export const CART = {
  ORDER_FROM_WEB: 0,
  ORDER_FROM_APP: 1,
  ORDER_FROM_POS_IN_STORE: 2,
  ORDER_FROM_POS_DELIVERY: 3,
  ORDER_FROM_POS_SHIPPER: 4,
};

export const ORDER_STATUS = {
  ALL: 'ALL',
  WAITING_FOR_PROGRESSING: 'WAITING_FOR_PROGRESSING',
  PACKING: 'PACKING',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  USER_CANCELLED: 'USER_CANCELLED',
  CUSTOMER_CANCELLED: 'CUSTOMER_CANCELLED',
  SHIPPING: 'SHIPPING',
  DELIVERY_ERROR: 'DELIVERY_ERROR',
  COMPLETED: 'COMPLETED',
  CUSTOMER_RETURNING: 'CUSTOMER_RETURNING',
  CUSTOMER_HAS_RETURNS: 'CUSTOMER_HAS_RETURNS',
  WAIT_FOR_PAYMENT: 'WAIT_FOR_PAYMENT',
};
